# Generated by Django 2.2.10 on 2020-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_banber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banber',
            new_name='Banner',
        ),
    ]
