# Generated by Django 2.2.10 on 2020-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20200227_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='展示优先级（越小越高）'),
        ),
    ]
