# Generated by Django 2.2.10 on 2020-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200225_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
